all_cards_stats = {
    'air': {'name': 'Airport', 'income': 20, 'popularity': 12, 'workers': 30, 'type': '1st'},
    'apart': {'name': 'Apartment', 'population': 20, 'income': 5, 'type': '1st'},
    'bank': {'name': 'Bank', 'income': 30, 'popularity': 10, 'workers': 20, 'type': '1st'},
    'basic': {'name': 'Basic Home', 'population': 4, 'income': 1, 'type': '1st'},
    'cinema': {'name': 'Cinema', 'income': 15, 'popularity': 8, 'workers': 20, 'type': '1st'},
    'circus': {'name': 'Circus', 'income': 10, 'popularity': 10, 'workers': 20, 'type': '1st'},
    'factory': {'name': 'Factory', 'income': 20, 'popularity': 5, 'workers': 40, 'type': '1st'},
    'garb': {'name': 'Garbage Dump', 'income': 0, 'popularity': -30, 'workers': 10, 'type': '1st'},
    'gym': {'name': 'Gym', 'income': 5, 'popularity': 8, 'workers': 6, 'type': '1st'},
    'hive': {'name': 'Hive Sign', 'income': 5, 'popularity': 20, 'workers': 7, 'type': '1st'},
    'lux': {'name': 'Luxury Home', 'population': 3, 'income': 2, 'type': '1st'},
    'ps': {'name': 'Police Station', 'income': 5, 'popularity': 6, 'workers': 15, 'type': '1st'},
    'res': {'name': 'Restaurant', 'income': 10, 'popularity': 8, 'workers': 10, 'type': '1st'},
    'sm': {'name': 'Shopping Mall', 'income': 15, 'popularity': 8, 'workers': 20, 'type': '1st'},
    'wd': {'name': 'Weed Dispensary', 'income': 10, 'popularity': 10, 'workers': 10, 'type': '1st'},
    'zoo': {'name': 'Zoo', 'income': 10, 'popularity': 8, 'workers': 20, 'type': '1st'},
    'ad': {'name': 'Ad Agency', 'income': 9, 'popularity': 5, 'workers': 6, 'creativity': '5', 'type': '2nd'},
    'art': {'name': 'Art Gallery', 'popularity': 12, 'workers': 5, 'creativity': '10', 'type': '2nd'},
    'brew': {'name': 'Brewery', 'income': 9, 'popularity': 5, 'workers': 10, 'type': '2nd'},
    'cas': {'name': 'Casino', 'income': 25, 'popularity': 8, 'workers': 10, 'type': '2nd'},
    'farm': {'name': 'Farm', 'population': 5, 'income': 6, 'popularity': 5, 'workers': 11, 'type': '2nd'},
    'forest': {'name': 'Forest', 'income': 4, 'popularity': 4, 'workers': 2, 'type': '2nd'},
    'hosp': {'name': 'Hospital', 'income': 5, 'popularity': 14, 'workers': 10, 'type': '2nd'},
    'hot': {'name': 'Hotel', 'population': 4, 'income': 10, 'popularity': 5, 'workers': 15, 'type': '2nd'},
    'job': {'name': 'Job Center', 'income': 5, 'popularity': 7, 'workers': 10, 'type': '2nd'},
    'lab': {'name': 'Laboratory', 'income': 6, 'popularity': 5, 'workers': 11, 'education': '6', 'type': '2nd'},
    'lawf': {'name': 'Law Firm', 'income': 10, 'popularity': 2, 'workers': 10, 'type': '2nd'},
    'mic': {'name': 'Military Industrial Complex', 'income': 20, 'popularity': -10, 'workers': 30, 'type': '2nd'},
    'nicl': {'name': 'Night Club', 'income': 8, 'popularity': 8, 'workers': 10, 'creativity': '3', 'type': '2nd'},
    'nucp': {'name': 'Nuclear Plant', 'income': 20, 'popularity': -15, 'workers': 15, 'type': '2nd'},
    'park': {'name': 'Park', 'population': 2, 'popularity': 5, 'workers': 1, 'type': '2nd'},
    'pubr': {'name': 'Public Restrooms', 'income': 2, 'popularity': -1, 'workers': 2, 'type': '2nd'},
    'resc': {'name': 'Research Center', 'income': 3, 'popularity': 5, 'workers': 18, 'education': '10', 'type': '2nd'},
    'sch': {'name': 'School', 'income': 2, 'popularity': 9, 'workers': 12, 'education': '5', 'type': '2nd'},
    'sao': {'name': 'Social Aid Office', 'income': 0, 'popularity': 5, 'workers': 40, 'type': '2nd'},
    'solp': {'name': 'Solar Plant', 'income': 5, 'popularity': 7, 'workers': 5, 'type': '2nd'},
    'stad': {'name': 'Stadium', 'income': 15, 'popularity': 10, 'workers': 17, 'type': '2nd'},
    'uni': {'name': 'University', 'income': 2, 'popularity': 9, 'workers': 14, 'education': '10', 'type': '2nd'},
    'wef': {'name': 'WEED Farm', 'income': 7, 'popularity': 5, 'workers': 8, 'type': '2nd'},
    'wave': {'name': 'Waves Broadcast Tower', 'income': 1, 'popularity': 5, 'workers': 1, 'creativity': '40', 'type': '2nd'},
    'wt': {'name': 'Wind Turbine', 'income': 3, 'popularity': -2, 'workers': 2, 'type': '2nd'},
    'barb': {'name': 'Barber Shop', 'income': 8, 'popularity': 7, 'workers': 3, 'type': '3rd'},
    'barr': {'name': 'Barracks', 'population': 4, 'popularity': -1, 'type': '3rd'},
    'cade': {'name': 'Car Dealership', 'income': 15, 'popularity': 10, 'workers': 9, 'type': '3rd'},
    'chur': {'name': 'Church', 'income': 1, 'popularity': 9, 'workers': 5, 'type': '3rd'},
    'coco': {'name': 'Construction Company', 'income': 10, 'popularity': 10, 'workers': 30, 'type': '3rd'},
    'cons': {'name': 'Construction Site', 'type': '3rd'},
    'court': {'name': 'Court', 'income': 5, 'popularity': -8, 'workers': 10, 'type': '3rd'},
    'fire': {'name': 'Fire Department', 'income': 3, 'popularity': 12, 'workers': 20, 'type': '3rd'},
    'grav': {'name': 'Graveyard', 'income': 2, 'popularity': -10, 'workers': 2, 'type': '3rd'},
    'ice': {'name': 'Ice Cream Shop', 'income': 8, 'popularity': 7, 'workers': 3, 'type': '3rd'},
    'mb': {'name': 'Military Base', 'income': 10, 'popularity': -30, 'workers': 100, 'type': '3rd'},
    'music': {'name': 'Music Store', 'income': 8, 'popularity': 7, 'workers': 3, 'type': '3rd'},
    'office': {'name': 'Office', 'income': 10, 'popularity': 5, 'workers': 20, 'type': '3rd'},
    'parking': {'name': 'Parking', 'income': 5, 'popularity': 2, 'workers': 5, 'type': '3rd'},
    'pizza': {'name': 'Pizzeria', 'income': 9, 'popularity': 7, 'workers': 6, 'type': '3rd'},
    'powl': {'name': 'Power Line', 'income': 6, 'popularity': -2, 'workers': 4, 'type': '3rd'},
    'prison': {'name': 'Prison', 'income': 1, 'popularity': -10, 'workers': 30, 'type': '3rd', 'load': 11},
    'ruins': {'name': 'Ruins', 'popularity': -30, 'type': '3rd'},
    'spa': {'name': 'Spa', 'income': 9, 'popularity': 11, 'workers': 7, 'type': '3rd'},
    'space': {'name': 'SpaceSIM Company', 'income': 5, 'popularity': 10, 'workers': 10, 'type': '3rd'},
    'tv': {'name': 'TV Station', 'income': 21, 'popularity': 13, 'workers': 20, 'type': '3rd'},
    'train': {'name': 'Train Station', 'income': 12, 'popularity': 9, 'workers': 20, 'type': '3rd'},
    'ware': {'name': 'Warehouse', 'type': '3rd'},
    'addcgambler': {'name': 'Addicted Gambler', 'population': 1, 'income': 1, 'popularity': -1, 'type': 'citizen'},
    'artist': {'name': 'Artist', 'population': 1, 'popularity': 0, 'type': 'citizen', 'creativity': '1'},
    'artists': {'name': 'Artists', 'population': 2, 'popularity': 0, 'type': 'citizen', 'creativity': '2'},
    'arch': {'name': 'Architect', 'population': 1, 'income': 1, 'popularity': 1, 'education': '1', 'type': 'citizen'},
    'dead': {'name': 'Dead Citizen', 'population': 0, 'popularity': -5, 'type': 'dead citizen', 'creativity': '0', 'income': -1, 'education': '0'},
    'doctor': {'name': 'Doctor', 'population': 1, 'popularity': 2, 'type': 'citizen', 'income': 1, 'education': '2'},
    'retired': {'name': 'Retired Citizen', 'population': 0, 'popularity': 3, 'type': 'citizen', 'income': 0, 'education': '0', 'creativity': '0'},
    'vip': {'name': 'VIP Citizen', 'type': 'citizen'},
    'criminal': {'name': 'Criminal', 'population': 1, 'popularity': -50, 'type': 'citizen', 'income': -1},
    'clown': {'name': 'Clown', 'income': 0, 'popularity': 50, 'type': 'citizen',
              'population': 1, 'education': '0', 'creativity': '10'},
    'econo': {'name': 'Economist', 'population': 1, 'popularity': 1, 'type': 'citizen', 'income': 3, 'education': '0'},
    'ecoact': {'name': 'Eco Activist', 'population': 1, 'popularity': -2,
               'type': 'citizen', 'income': 0, 'education': 0, 'creativity': 0},
    'engineer': {'name': 'Engineer', 'population': 1, 'popularity': 1, 'type': 'citizen',
                 'income': 0, 'education': '2'},
    'expr': {'name': 'Executive Producer', 'type': 'citizen'},
    'gamb': {'name': 'Gambler', 'population': 1, 'popularity': -1, 'type': 'citizen'},
    'gamer': {'name': 'Gamer', 'population': 1, 'type': 'citizen'},
    'hack_1': {'name': 'Hacker', 'income': 0, 'popularity': 1, 'type': 'citizen',
               'population': 1, 'education': 1, 'creativity': 0},
    'hack_2': {'name': 'Hacker', 'income': 0, 'popularity': 1, 'type': 'citizen',
               'population': 1, 'education': 2, 'creativity': 0},
    'hack_3': {'name': 'Hacker', 'income': 0, 'popularity': 1, 'type': 'citizen',
               'population': 1, 'education': 3, 'creativity': 0},
    'hack_4': {'name': 'Hacker', 'income': 0, 'popularity': 1, 'type': 'citizen',
               'population': 1, 'education': 4, 'creativity': 0},
    'hack_5': {'name': 'Hacker', 'population': 1, 'popularity': 1, 'type': 'citizen', 'income': 0, 'education': '5', 'creativity': '1'},
    'homeless': {'name': 'Homeless', 'population': 1, 'popularity': -1, 'type': 'citizen'},
    'hwork': {'name': 'Hard Worker', 'population': 1, 'income': 1, 'type': 'citizen'},
    'immigrant': {'name': 'Immigrants', 'population': 2, 'popularity': -2, 'type': 'citizen'},
    'invest': {'name': 'Investor', 'population': 1, 'income': 2, 'popularity': 1,
               'education': '1', 'type': 'citizen'},
    'influencer': {'name': 'Influencer', 'population': 1, 'popularity': 2, 'type': 'citizen',
                   'income': 1, 'creativity': '2'},
    'lawyer': {'name': 'Lawyer', 'income': 0, 'popularity': 2, 'type': 'citizen',
               'population': 1, 'education': '0', 'creativity': '0'},
    'policeman': {'name': 'Policeman', 'income': 0, 'popularity': 1, 'type': 'citizen',
                  'population': 1, 'education': '0', 'creativity': '0'},
    'politician': {'name': 'Politician', 'income': -40, 'popularity': -20, 'type': 'citizen',
                   'population': 1, 'education': '0', 'creativity': '0'},
    'priest': {'name': 'Priest', 'population': 1, 'income': -2, 'popularity': 1,
               'education': '1', 'type': 'citizen'},
    'progamer': {'name': 'ProGamer', 'population': 1, 'income': 1, 'type': 'citizen'},
    'prof': {'name': 'Professor', 'population': 1, 'popularity': 3, 'type': 'citizen', 'income': 0, 'education': '3'},
    'sct': {'name': 'Scientist', 'population': 1, 'popularity': 0, 'type': 'citizen', 'education': '1'},
    'scs': {'name': 'Scientists', 'population': 2, 'popularity': 0, 'type': 'citizen', 'education': '2'},
    'sick': {'name': 'Sick Citizen', 'population': 1, 'popularity': -3, 'type': 'citizen',
             'income': -3, 'education': '0', 'creativity': '0'},
    'sold': {'name': 'Soldier', 'population': 1, 'popularity': -2, 'type': 'citizen', 'income': 0, 'education': '0'},
    'supcit': {'name': 'Super Citizen', 'population': 1, 'popularity': 40, 'type': 'citizen', 'income': -5,
               'education': '0', 'creativity': '0'},
    'student': {'name': 'Student', 'income': 0, 'popularity': 1, 'type': 'citizen',
                'population': 1, 'education': '0', 'creativity': '0'},
    'studentdebt': {'name': 'Student (debt)', 'type': 'citizen'},
    'supcop': {'name': 'Super Cop', 'population': 1, 'popularity': -10, 'type': 'citizen', 'education': '0',
               'income': -10, 'creativity': '0'},
    'supcrim': {'name': 'Super Criminal', 'population': 1, 'popularity': 20, 'type': 'citizen',
                'income': 20, 'education': '0', 'creativity': '0'},
    'supsol': {'name': 'Super Soldier', 'population': 1, 'popularity': -20, 'type': 'citizen',
               'income': -20, 'education': '0', 'creativity': '0'},
    'teacher': {'name': 'Teacher', 'income': -3, 'popularity': 1, 'type': 'citizen',
                'population': 1, 'education': '2', 'creativity': '0'},
    'trad': {'name': 'Trader', 'population': 1, 'income': 2, 'popularity': -1, 'type': 'citizen'},
    'worker' : {'name': 'Worker', 'population': 1, 'popularity': 0, 'type': 'citizen'},
    'workers': {'name': 'Worker', 'population': 1, 'popularity': 0, 'type': 'citizen'},
    'young': {'name': 'Young Citizen', 'income': -1, 'popularity': 2, 'type': 'citizen'},
    'artm': {'name': 'Art Museum', 'income': 20, 'popularity': 90, 'workers': 70,
             'creativity': '100', 'type': 'combined'},
    'databtc': {'name': 'BTC Datacenter', 'workers': 120, 'type': 'combined'},
    'dataeth': {'name': 'ETH Datacenter', 'workers': 120, 'type': 'combined'},
    'datahive': {'name': 'Hive Datacenter', 'workers': 120, 'type': 'combined'},
    'cenb': {'name': 'Central Bank', 'income': 215, 'popularity': 0, 'workers': 150, 'type': 'combined'},
    'comh': {'name': 'Communal Housing', 'population': 125, 'popularity': 30, 'workers': 10, 'type': 'combined'},
    'dopws': {'name': 'Doppler Weather Station', 'income': 5, 'popularity': 15,
              'workers': 60, 'education': '20', 'type': 'combined'},
    'dron': {'name': 'Drone Factory', 'income': 130, 'popularity': -50, 'workers': 210, 'type': 'combined'},
    'enzo': {'name': 'Entertainment Zone', 'income': 100, 'popularity': 80, 'workers': 100, 'type': 'combined'},
    'expl': {'name': 'Experimental Lab', 'income': 60, 'popularity': 10, 'workers': 120, 'type': 'combined'},
    'faco': {'name': 'Farm Corporation', 'income': 260, 'workers': 200, 'type': 'combined'},
    'golf': {'name': 'Golf Course', 'income': 40, 'popularity': 80, 'workers': 50, 'type': 'combined'},
    'indz': {'name': 'Industrial Zone', 'income': 800, 'popularity': 100, 'workers': 1000, 'type': 'combined'},
    'mecrp': {'name': 'Media Corporation', 'type': 'combined'},
    'migcen': {'name': 'Migration Center', 'population': 50, 'income': -80,
               'popularity': 20, 'workers': 110, 'type': 'combined'},
    'luxst': {'name': 'Luxury Street', 'population': 100, 'income': -100,
              'popularity': 350, 'workers': 500, 'type': 'combined'},
    'modho': {'name': 'Modern Home', 'population': 3, 'income': -1, 'popularity': 1, 'type': 'combined'},
    'natzo': {'name': 'Nature Zone', 'population': 5, 'income': -10, 'popularity': 250, 'workers': 10, 'type': 'combined'},
    'natfarm': {'name': 'Natural Farm', 'income': -20, 'popularity': 150, 'workers': 100, 'type': 'combined'},
    'pola': {'name': 'Police Academy', 'income': 30, 'popularity': 40, 'workers': 90, 'type': 'combined'},
    'poll': {'name': 'Police Lab', 'income': 30, 'popularity': 40, 'workers': 60, 'type': 'combined'},
    'pows': {'name': 'Power Distributor', 'income': 80, 'popularity': -25, 'workers': 60, 'type': 'combined'},
    'retho': {'name': 'Retirement Home', 'type': 'combined'},
    'smc': {'name': 'Social Media Company', 'type': 'combined'},
    'towru': {'name': 'Tower Ruins', 'type': 'combined'},
    'trhu': {'name': 'Transportation Hub', 'income': 190, 'popularity': 120, 'workers': 300, 'type': 'combined'},
    'unic': {'name': 'University Campus', 'income': 40, 'popularity': 110, 'workers': 200, 'type': 'combined'},
    'tempx': {'name': 'X Temple', 'workers': 120, 'type': 'combined'},
    'tempy': {'name': 'Y Temple', 'workers': 120, 'type': 'combined'},
    'tempZ': {'name': 'Z Temple', 'workers': 120, 'type': 'combined'},
    'pole': {'name': 'Police Equipment', 'type': 'tech'},
    'dront': {'name': 'Drone Technology', 'type': 'tech'},
    'robo': {'name': 'RoboCop', 'type': 'tech'},
    'neur': {'name': 'Neural Network', 'type': 'tech'},
    'vts': {'name': 'Voice to Skull', 'type': 'tech'},
    'finc': {'name': 'Free Internet Connection', 'type': 'tech'},
    'bdop': {'name': 'Better Documentation Practice', 'type': 'tech'},
    'opso': {'name': 'Open Source', 'type': 'tech'},
    'fred': {'name': 'Free Education', 'type': 'tech'},
    'advt': {'name': 'Advanced Training', 'type': 'tech'},
    'baau': {'name': 'Basic Automation', 'type': 'tech'},
    'faub': {'name': 'Full Automated Brewery', 'type': 'tech'},
    'aite': {'name': 'AI Technology', 'type': 'tech'},
    'min-h': {'name': 'Mining Operation - HIVE', 'type': 'tech'},
    'min-e': {'name': 'Mining Operation - ETH', 'type': 'tech'},
    'min-b': {'name': 'Mining Operation - BTC', 'type': 'tech'},
    'advr': {'name': 'Advanced Robotics', 'type': 'tech'},
    'gmof': {'name': 'GMO Farming', 'type': 'tech'},
    'ecoe': {'name': 'ECO Energy', 'type': 'tech'},
    'cold': {'name': 'Cold Fusion', 'type': 'tech'},
    'dyss': {'name': 'Dyson Sphere', 'type': 'tech'},
    'adre': {'name': 'Advanced Recycling', 'type': 'tech'},
    'baac': {'name': 'Basic Accounting', 'type': 'tech'},
    'priu': {'name': 'Printers Upgrade', 'type': 'tech'},
    'defi': {'name': 'DEFI', 'type': 'tech'},
    'bitf': {'name': 'Bitcoin Fund', 'type': 'tech'},
    'apra': {'name': 'Advanced Prayer', 'type': 'tech'},
    'tohu': {'name': 'Tests on Humans', 'type': 'tech'},
    'exhe': {'name': 'Experimental Healthcare', 'type': 'tech'},
    'heai': {'name': 'Healthcare AI', 'type': 'tech'},
    'ahea': {'name': 'Advanced Healthcare', 'type': 'tech'},
    'admng': {'name': 'Advanced Management', 'type': 'tech'},
    'prep': {'name': 'Prepared Police', 'type': ''},
    'cris': {'name': 'Crisis Bond',  'type': ''},
    'dust': {'name': 'Dust', 'population': 0, 'income': -1, 'popularity': -1, 'workers': 1},
    'energyp': {'name': 'Energy Reload', 'type': ''},
    'vaccine': {'name': 'Vaccine', 'type': ''},
    'asia': {'name': 'Asia', 'type': 'background'},
    'atlantis': {'name': 'Atlantis', 'type': 'background'},
    'lake': {'name': 'Lake', 'type': 'background'},
    'rockies': {'name': 'Rockies', 'type': 'background'},
    'snow': {'name': 'Snow', 'type': 'background'},
    'sky': {'name': 'Clear Sky', 'type': 'background'},
    'egypt': {'name': 'Egypt', 'type': 'background'},
    'everest': {'name': 'Everest', 'type': 'background'},
    'mountains': {'name': 'Mountains', 'type': 'background'},
    'night': {'name': 'Night', 'type': 'background'},
    'fish': {'name': 'Fish', 'type': 'animation'},
    'clouds': {'name': 'Clouds', 'type': 'animation'},
    'ufo': {'name': 'Unidentified Flying Object'}
}