all_cards = {
    'air': {'name': 'Airport', 'type': '1st'},
    'apart': {'name': 'Apartment', 'type': '1st'},
    'bank': {'name': 'Bank', 'type': '1st'},
    'basic': {'name': 'Basic Home', 'type': '1st'},
    'cinema': {'name': 'Cinema', 'type': '1st'},
    'circus': {'name': 'Circus', 'type': '1st'},
    'factory': {'name': 'Factory', 'type': '1st'},
    'garb': {'name': 'Garbage Dump', 'type': '1st'},
    'gym': {'name': 'Gym', 'type': '1st'},
    'hive': {'name': 'Hive Sign', 'type': '1st'},
    'lux': {'name': 'Luxury Home', 'type': '1st'},
    'ps': {'name': 'Police Station', 'type': '1st'},
    'res': {'name': 'Restaurant', 'type': '1st'},
    'sm': {'name': 'Shopping Mall', 'type': '1st'},
    'wd': {'name': 'Weed Dispensary', 'type': '1st'},
    'zoo': {'name': 'Zoo', 'type': '1st'},
    'ad': {'name': 'Ad Agency', 'type': '2nd'},
    'art': {'name': 'Art Gallery', 'type': '2nd'},
    'brew': {'name': 'Brewery', 'type': '2nd'},
    'cas': {'name': 'Casino', 'type': '2nd'},
    'farm': {'name': 'Farm', 'type': '2nd'},
    'forest': {'name': 'Forest', 'type': '2nd'},
    'hosp': {'name': 'Hospital', 'type': '2nd'},
    'hot': {'name': 'Hotel', 'type': '2nd'},
    'job': {'name': 'Job Center', 'type': '2nd'},
    'lab': {'name': 'Laboratory', 'type': '2nd'},
    'lawf': {'name': 'Law Firm', 'type': '2nd'},
    'mic': {'name': 'Military Industrial Complex', 'type': '2nd'},
    'nicl': {'name': 'Night Club', 'type': '2nd'},
    'nucp': {'name': 'Nuclear Plant', 'type': '2nd'},
    'park': {'name': 'Park',  'type': '2nd'},
    'pubr': {'name': 'Public Restrooms', 'type': '2nd'},
    'resc': {'name': 'Research Center', 'type': '2nd'},
    'sch': {'name': 'School', 'type': '2nd'},
    'sao': {'name': 'Social Aid Office', 'type': '2nd'},
    'solp': {'name': 'Solar Plant', 'type': '2nd'},
    'stad': {'name': 'Stadium', 'type': '2nd'},
    'uni': {'name': 'University', 'type': '2nd'},
    'wef': {'name': 'WEED Farm', 'type': '2nd'},
    'wave': {'name': 'Waves Broadcast Tower', 'type': '2nd'},
    'wt': {'name': 'Wind Turbine', 'type': '2nd'},
    'barb': {'name': 'Barber Shop', 'type': '3rd'},
    'barr': {'name': 'Barracks', 'type': '3rd'},
    'cade': {'name': 'Car Dealership', 'type': '3rd'},
    'chur': {'name': 'Church', 'type': '3rd'},
    'coco': {'name': 'Construction Company', 'type': '3rd'},
    'cons': {'name': 'Construction Site', 'type': '3rd'},
    'court': {'name': 'Court', 'type': '3rd'},
    'fire': {'name': 'Fire Department', 'type': '3rd'},
    'grav': {'name': 'Graveyard', 'type': '3rd'},
    'ice': {'name': 'Ice Cream Shop', 'type': '3rd'},
    'mb': {'name': 'Military Base', 'type': '3rd'},
    'music': {'name': 'Music Store', 'type': '3rd'},
    'office': {'name': 'Office', 'type': '3rd'},
    'parking': {'name': 'Parking', 'type': '3rd'},
    'pizza': {'name': 'Pizzeria', 'type': '3rd'},
    'powl': {'name': 'Power Line', 'type': '3rd'},
    'prison': {'name': 'Prison', 'type': '3rd'},
    'ruins': {'name': 'Ruins', 'type': '3rd'},
    'spa': {'name': 'Spa', 'type': '3rd'},
    'space': {'name': 'SpaceSIM Company', 'type': '3rd'},
    'tv': {'name': 'TV Station', 'type': '3rd'},
    'train': {'name': 'Train Station', 'type': '3rd'},
    'ware': {'name': 'Warehouse', 'type': '3rd'},
    'addcgambler': {'name': 'Addicted Gambler','type': 'citizen'},
    'artist': {'name': 'Artist', 'type': 'citizen'},
    'arch': {'name': 'Architect', 'type': 'citizen'},
    'dead': {'name': 'Dead Citizen', 'type': 'dead citizen'},
    'retired': {'name': 'Retired Citizen', 'type': 'citizen'},
    'vip': {'name': 'VIP Citizen', 'type': 'citizen'},
    'criminal': {'name': 'Criminal', 'type': 'citizen'},
    'clown': {'name': 'Clown', 'type': 'citizen'},
    'doctor': {'name': 'Doctor', 'type': 'citizen'},
    'econo': {'name': 'Economist', 'type': 'citizen'},
    'ecoact': {'name': 'Eco Activist', 'type': 'citizen'},
    'engineer': {'name': 'Engineer', 'type': 'citizen'},
    'expr': {'name': 'Executive Producer', 'type': 'citizen'},
    'gamb': {'name': 'Gambler', 'type': 'citizen'},
    'gamer': {'name': 'Gamer', 'type': 'citizen'},
    'hack_1': {'name': 'Hacker', 'type': 'citizen'},
    'hack_2': {'name': 'Hacker 2', 'type': 'citizen'},
    'hack_3': {'name': 'Hacker 3', 'type': 'citizen'},
    'hack_4': {'name': 'Hacker 4', 'type': 'citizen'},
    'hack_5': {'name': 'Hacker 5', 'type': 'citizen'},
    'homeless': {'name': 'Homeless', 'type': 'citizen'},
    'hwork': {'name': 'Hard Worker', 'type': 'citizen'},
    'invest': {'name': 'Investor', 'type': 'citizen'},
    'influencer': {'name': 'Influencer', 'type': 'citizen'},
    'lawyer': {'name': 'Lawyer', 'type': 'citizen'},
    'policeman': {'name': 'Policeman', 'type': 'citizen'},
    'politician': {'name': 'Politician', 'type': 'citizen'},
    'priest': {'name': 'Priest', 'type': 'citizen'},
    'progamer': {'name': 'ProGamer', 'type': 'citizen'},
    'prof': {'name': 'Professor', 'type': 'citizen'},
    'sct': {'name': 'Scientist', 'type': 'citizen'},
    'scs': {'name': 'Scientists', 'type': 'citizen'},
    'sick': {'name': 'Sick Citizen', 'type': 'citizen'},
    'sold': {'name': 'Soldier', 'type': 'citizen'},
    'supcit': {'name': 'Super Citizen', 'type': 'citizen'},
    'student': {'name': 'Student', 'type': 'citizen'},
    'studentdebt': {'name': 'Student (debt)', 'type': 'citizen'},
    'supcop': {'name': 'Super Cop', 'type': 'citizen'},
    'supcrim': {'name': 'Super Criminal', 'type': 'citizen'},
    'supsol': {'name': 'Super Soldier', 'type': 'citizen'},
    'teacher': {'name': 'Teacher', 'type': 'citizen'},
    'trad': {'name': 'Trader', 'type': 'citizen'},
    'worker' : {'name': 'Worker', 'type': 'citizen'},
    'workers': {'name': 'Workers', 'type': 'citizen'},
    'young': {'name': 'Young Citizen', 'type': 'citizen'},
    'artm': {'name': 'Art Museum', 'type': 'combined'},
    'databtc': {'name': 'BTC Datacenter', 'type': 'combined'},
    'dataeth': {'name': 'ETH Datacenter', 'type': 'combined'},
    'datahive': {'name': 'Hive Datacenter', 'type': 'combined'},
    'cenb': {'name': 'Central Bank', 'type': 'combined'},
    'comh': {'name': 'Communal Housing', 'type': 'combined'},
    'dopws': {'name': 'Doppler Weather Station', 'type': 'combined'},
    'dron': {'name': 'Drone Factory', 'type': 'combined'},
    'enzo': {'name': 'Entertainment Zone', 'type': 'combined'},
    'expl': {'name': 'Experimental Lab', 'type': 'combined'},
    'faco': {'name': 'Farm Corporation', 'type': 'combined'},
    'golf': {'name': 'Golf Course', 'type': 'combined'},
    'indz': {'name': 'Industrial Zone', 'type': 'combined'},
    'mecrp': {'name': 'Media Corporation', 'type': 'combined'},
    'migcen': {'name': 'Migraction Center', 'type': 'combined'},
    'luxst': {'name': 'Luxury Street', 'type': 'combined'},
    'modho': {'name': 'Modern Home', 'type': 'combined'},
    'natzo': {'name': 'Nature Zone', 'type': 'combined'},
    'natfarm': {'name': 'Natural Farm', 'type': 'combined'},
    'pola': {'name': 'Police Academy', 'type': 'combined'},
    'poll': {'name': 'Police Lab', 'type': 'combined'},
    'pows': {'name': 'Power Distributor', 'type': 'combined'},
    'retho': {'name': 'Retirement Home', 'type': 'combined'},
    'towru': {'name': 'Tower Ruins', 'type': 'combined'},
    'trhu': {'name': 'Transportation Hub', 'type': 'combined'},
    'unic': {'name': 'University Campus', 'type': 'combined'},
    'tempx': {'name': 'X Temple', 'type': 'combined'},
    'tempy': {'name': 'Y Temple', 'type': 'combined'},
    'tempZ': {'name': 'Z Temple', 'type': 'combined'},
    'pole': {'name': 'Police Equipment', 'type': 'tech'},
    'dront': {'name': 'Drone Technology', 'type': 'tech'},
    'robo': {'name': 'RoboCop', 'type': 'tech'},
    'neur': {'name': 'Neural Network', 'type': 'tech'},
    'vts': {'name': 'Voice to Skull', 'type': 'tech'},
    'finc': {'name': 'Free Internet Connection', 'type': 'tech'},
    'bdop': {'name': 'Better Documentation Practice', 'type': 'tech'},
    'opso': {'name': 'Open Source', 'type': 'tech'},
    'fred': {'name': 'Free Education', 'type': 'tech'},
    'advt': {'name': 'Advanced Training', 'type': 'tech'},
    'baau': {'name': 'Basic Automation', 'type': 'tech'},
    'faub': {'name': 'Full-Auto. Brewery', 'type': 'tech'},
    'aite': {'name': 'AI Technology', 'type': 'tech'},
    'min-h': {'name': 'Mining Operation - HIVE', 'type': 'tech'},
    'min-e': {'name': 'Mining Operation - ETH', 'type': 'tech'},
    'min-b': {'name': 'Mining Operation - BTC', 'type': 'tech'},
    'advr': {'name': 'Advanced Robotics', 'type': 'tech'},
    'gmof': {'name': 'GMO Farming', 'type': 'tech'},
    'ecoe': {'name': 'ECO Energy', 'type': 'tech'},
    'cold': {'name': 'Cold Fusion', 'type': 'tech'},
    'dyss': {'name': 'Dyson Sphere', 'type': 'tech'},
    'adre': {'name': 'Advanced Recycling', 'type': 'tech'},
    'baac': {'name': 'Basic Accounting', 'type': 'tech'},
    'priu': {'name': 'Printers Upgrade', 'type': 'tech'},
    'defi': {'name': 'DEFI', 'type': 'tech'},
    'bitf': {'name': 'Bitcoin Fund', 'type': 'tech'},
    'apra': {'name': 'Advanced Prayer', 'type': 'tech'},
    'tohu': {'name': 'Tests on Humans', 'type': 'tech'},
    'exhe': {'name': 'Experimental Healthcare', 'type': 'tech'},
    'heai': {'name': 'Healthcare AI', 'type': 'tech'},
    'ahea': {'name': 'Advanced Healthcare', 'type': 'tech'},
    'admng': {'name': 'Advanced Management', 'type': 'tech'},
    'prep': {'name': 'Prepared Police', 'type': 'other'},
    'cris': {'name': 'Crisis Bond', 'type': 'other'},
    'dust': {'name': 'Dust', 'type': 'other'},
    'energyp': {'name': 'Energy Reload', 'type': 'other'},
    'vaccine': {'name': 'Vaccine', 'type': 'other'},
    'asia': {'name': 'Asia', 'type': 'background'},
    'atlantis': {'name': 'Atlantis', 'type': 'background'},
    'lake': {'name': 'Lake', 'type': 'background'},
    'rockies': {'name': 'Rockies', 'type': 'background'},
    'snow': {'name': 'Snow', 'type': 'background'},
    'sky': {'name': 'Clear Sky', 'type': 'background'},
    'egypt': {'name': 'Egypt', 'type': 'background'},
    'everest': {'name': 'Everest', 'type': 'background'},
    'mountains': {'name': 'Mountains', 'type': 'background'},
    'night': {'name': 'Night', 'type': 'background'},
    'clouds': {'name': 'Clouds', 'type': 'animation'},
    'ufo': {'name': 'Unidentified Flying Object', 'type': 'other'}
}